version: '3'

services:
  cities:
    image: cities-suggestions
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 2345:2345
    volumes:
      - .env:/home/app/.env
    environment:
      CITIES_REPOSITORY_STRATEGY: ${CITIES_REPOSITORY_STRATEGY:-mongo}
      CITIES_REPOSITORY_MONGO_URI: ${CITIES_REPOSITORY_MONGO_URI:-mongodb://root:secret@localhost:27017/development?authSource=admin}
  mongo:
    image: mongo:4.4.2
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
